# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17GYITXcWhk6J6T_QPiK_4PP-XlwM69Pq
"""

import streamlit as st
import pickle
import numpy as np

# Load saved scaler and model
scaler = pickle.load(open('scaler2.pkl', 'rb'))
model = pickle.load(open('kmeans2.pkl', 'rb'))

st.title("🌍 Country Clustering App")

st.write("Enter the details below:")

# User Inputs
gdp = st.number_input("GDP", value=10000.0)
birth_rate = st.number_input("Birth Rate", value=20.0)
co2 = st.number_input("CO2 Emissions", value=5.0)

# Predict button
if st.button("Predict Cluster"):

    # Arrange input in same order as training
    input_data = np.array([[gdp, birth_rate, co2]])

    # Scale input
    scaled_data = scaler.transform(input_data)

    # Predict cluster
    cluster = model.predict(scaled_data)

    st.success(f"Predicted Cluster: {cluster[0]}")